/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.itson.cliente.Cliente;
import com.itson.dominio.Jugador;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ModeloInicio;
import util.AvatarManager;

/**
 *
 * @author 
 */
public class FrmConfigurarJugador extends javax.swing.JFrame {

    /**
     * Creates new form FrmConfigurarJugador
     */
    private AvatarManager avatars;
    private ModeloInicio inicio;
    public FrmConfigurarJugador() {
        initComponents();
        this.avatars=new AvatarManager(this.lblAvatar);
        this.avatars.init();
        setLocationRelativeTo(null);
    }
    public FrmConfigurarJugador(ModeloInicio inicio) {
        initComponents();
        setLocationRelativeTo(null);
        this.avatars=new AvatarManager(this.lblAvatar);
        this.avatars.init();
        this.inicio=inicio;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        btnConfirmarNombre = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        btnConfirmarNombre1 = new javax.swing.JButton();
        btnConfirmarNombre2 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblSeleccionarColor = new javax.swing.JLabel();
        rbtnColor6 = new javax.swing.JRadioButton();
        rbtnColor5 = new javax.swing.JRadioButton();
        rbtnColor4 = new javax.swing.JRadioButton();
        rbtnColor3 = new javax.swing.JRadioButton();
        rbtnColor2 = new javax.swing.JRadioButton();
        rbtnColor1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnConfirmarNombre.setText("▶");
        btnConfirmarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNombreActionPerformed(evt);
            }
        });

        lblAvatar.setText("<Avatar>");
        lblAvatar.setMaximumSize(new java.awt.Dimension(200, 200));
        lblAvatar.setMinimumSize(new java.awt.Dimension(200, 200));
        lblAvatar.setPreferredSize(new java.awt.Dimension(200, 200));

        btnConfirmarNombre1.setText("✔");
        btnConfirmarNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNombre1ActionPerformed(evt);
            }
        });

        btnConfirmarNombre2.setText("◀");
        btnConfirmarNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarNombre2ActionPerformed(evt);
            }
        });

        btnRegresar.setText("↩");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblSeleccionarColor.setText("Selecciona un color para las fichas");

        rbtnColor6.setBackground(new java.awt.Color(0, 153, 255));

        rbtnColor5.setBackground(new java.awt.Color(204, 0, 204));

        rbtnColor4.setBackground(new java.awt.Color(130, 146, 203));

        rbtnColor3.setBackground(new java.awt.Color(0, 204, 0));

        rbtnColor2.setBackground(new java.awt.Color(255, 0, 204));

        rbtnColor1.setBackground(new java.awt.Color(204, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnConfirmarNombre2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNombreUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmarNombre1))
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirmarNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarColor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnColor1)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnColor2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnColor3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnColor4)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnColor5)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnColor6)))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarNombre)
                            .addComponent(btnConfirmarNombre2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarNombre1)))
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblSeleccionarColor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnColor5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnColor6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnColor4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnColor2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnColor3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnColor1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            this.dispose();
            this.inicio.getJugador().nombre=this.txtNombreUsuario.getText();
            this.inicio.getJugador().avatar=this.avatars.getActualUri();
            this.inicio.notificar(inicio);
            Color color= new Color(0);
            if(rbtnColor1.isSelected()){
                color=Color.RED;
            }
            if(rbtnColor2.isSelected()){
                color=Color.BLUE;
            }
            if(rbtnColor3.isSelected()){
                color=Color.GREEN;
            }
            if(rbtnColor4.isSelected()){
                color=Color.YELLOW;
            }
            if(rbtnColor5.isSelected()){
                color=Color.MAGENTA;
            }
            if(rbtnColor6.isSelected()){
                color=Color.cyan;
            }
            Cliente.getInstance().getOu().writeUTF("CONFIGURARJUGADOR");
            Cliente.getInstance().getOu().flush();
            Cliente.getInstance().getOu().writeObject(new Jugador(this.inicio.getJugador().nombre,color,this.inicio.getJugador().avatar,null));
            Cliente.getInstance().getOu().flush();
        } catch (IOException ex) {
            Logger.getLogger(FrmConfigurarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConfirmarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarNombreActionPerformed
        this.avatars.next();
    }//GEN-LAST:event_btnConfirmarNombreActionPerformed

    private void btnConfirmarNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarNombre2ActionPerformed
        this.avatars.previous();
    }//GEN-LAST:event_btnConfirmarNombre2ActionPerformed

    private void btnConfirmarNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarNombre1ActionPerformed
        if(!this.txtNombreUsuario.getText().isBlank()){
            this.txtNombreUsuario.setEnabled(false);
        }
    }//GEN-LAST:event_btnConfirmarNombre1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfigurarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfigurarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConfirmarNombre;
    private javax.swing.JButton btnConfirmarNombre1;
    private javax.swing.JButton btnConfirmarNombre2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblSeleccionarColor;
    private javax.swing.JRadioButton rbtnColor1;
    private javax.swing.JRadioButton rbtnColor2;
    private javax.swing.JRadioButton rbtnColor3;
    private javax.swing.JRadioButton rbtnColor4;
    private javax.swing.JRadioButton rbtnColor5;
    private javax.swing.JRadioButton rbtnColor6;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
