/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import dominio.FichaNumero;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author José Alcalá 180872
 */
public class frmTablero extends javax.swing.JFrame {
    private List<JButton> botones;
    private int indice;
    public int maximoFichas;
    public List<JButton> fichas;

    
    public int getMaximoFichas() {
        return maximoFichas;
    }

    /**
     * Creates new form frmTablero
     */
    public void setMaximoFichas(int maximoFichas) {    
        this.maximoFichas = maximoFichas;
    }

  

    public frmTablero() {
        initComponents();
        botones = new ArrayList<>();
        indice = 0;
        ArrayList<Integer> pozo=new ArrayList<>();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        btnPozo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(panel);

        btnPozo.setText("pozo(+)");
        btnPozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPozoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPozo)
                        .addGap(0, 333, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnPozo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        JButton boton = new JButton("Boton " + indice);
        panel.add(boton);
        botones.add(boton);
        indice++;
        panel.updateUI();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnPozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPozoActionPerformed
        System.out.println("El maximo de fichas son: "+maximoFichas);
        fichas = new ArrayList<>();
        ArrayList<FichaNumero> ficha=new ArrayList<>();
        
            for (int i = 0; i < 2; i++) {
            //rojas
            for (int j = 1; j < maximoFichas+1; j++) {
                System.out.println("Ficha amarillas: "+j);
                JButton boton = new JButton("amarillo " + j);
                panel.add(boton);
                fichas.add(boton);                
                panel.updateUI();
            }
            //amarillas
            for (int k = 1; k < maximoFichas+1; k++) {
                System.out.println("Ficha amarillas: "+k);
                JButton boton = new JButton("amarillo " + k);
                panel.add(boton);
                fichas.add(boton);                
                panel.updateUI();
            }
            //verdes
            for (int l = 1; l < maximoFichas+1; l++) {
                System.out.println("Ficha verdes: "+l);
                JButton boton = new JButton("verde " + l);
                panel.add(boton);
                fichas.add(boton);                
                panel.updateUI();
            }
            //negras
            for (int m = 1; m < maximoFichas+1; m++) {
                System.out.println("Ficha negras: "+m);
                JButton boton = new JButton("negro " + m);
                panel.add(boton);
                fichas.add(boton);                
                panel.updateUI();
            }
        }               
    }//GEN-LAST:event_btnPozoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPozo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
